[package]
name = "bevy_serverkit"
version = "0.1.0"
edition = "2024"
autoexamples = false

[[example]]
name = "player_database"
path = "examples/player_database.rs"

[dependencies]
bevy = "0.18.1"
postgres = { version = "0.19.13", features = ["with-serde_json-1"] }
serde = "1.0.228"
serde_json = "1.0.149"
toml = "1.1.2"
